databases:
    - name: cimangi
      databaseName: cimangi
      user: cimangi
      plan: free

services:
    - type: web
      name: cimangi
      runtime: ruby
      plan: free
      buildCommand: './bin/render-build.sh'
      # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
      startCommand: './bin/rails server'
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: cimangi
                property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false
          - key: WEB_CONCURRENCY
            value: 2 # sensible default